#!/bin/bash -eu

NUM_FILES_MOVED="$1"

function log () {
  echo "$( date )" >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

if [ $NUM_FILES_MOVED -gt 0 ]
then
  log "Sending SNS message for moved files."

  source /root/.teslaCamSNSTopicARN

  python3 /root/bin/send_sns.py -t $sns_topic_arn -m "$NUM_FILES_MOVED file(s) were copied."
fi
